<a href="https://colab.research.google.com/github/abebae72/abebae.github.io/blob/main/Logistic_Regression_Example_4_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Lecture 20 Logistic Regression Example 4

In [74]:
import pandas as pd
import numpy as np
fish = pd.read_csv('https://bit.ly/fish_csv_data')

In [75]:
fish.head()          #  First 5 Sample Data among a Total 159 Data 

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [76]:
print(pd.unique(fish['Species']))     # Types of Classified Variables

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [77]:
# Predictor Variables:   x1: Weight,  x2: Length,  x3: Diagonal,  x4: Height,  x5: Width                
# Classified Variables:  Species: "Bream", "Roach", "Whitefish", "Parkki", "Perch", "Pike", "Smelt"
# hw() = w0 + w1 x1 + w2 x2 + w3 x3 + w4 x4 + w5 x5 

In [78]:
fish.describe()      #  Brief Information of a Total 159 Sample Data 

Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [79]:
fish_input = fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']]. to_numpy()     #  Input Data Preparation

In [80]:
fish_target = fish['Species']. to_numpy()                                              #  Target Data Preparation

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, test_size=0.2, random_state=42)     #  Training/Test Split

In [83]:
print(train_input.shape, test_input.shape)

(127, 5) (32, 5)


In [84]:
from sklearn.preprocessing import StandardScaler        #  Data Preprecessing for Input for "Train" and "Target"

In [85]:
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [86]:
from sklearn.linear_model import LogisticRegression

In [87]:
LR = LogisticRegression(C=20, max_iter=1000)

In [70]:
LR.fit(train_scaled, train_target)

LogisticRegression(C=20, max_iter=1000)

In [71]:
print(LR.score(train_scaled, train_target))   # Accuracy of Training Data
print(LR.score(test_scaled, test_target))     # Accuracy of Test Data

0.9291338582677166
0.90625


In [72]:
print(LR.predict(test_scaled[:5]))

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']


In [51]:
proba = LR.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=3))

[[0.    0.011 0.858 0.    0.123 0.006 0.003]
 [0.    0.003 0.043 0.    0.006 0.948 0.   ]
 [0.    0.    0.033 0.935 0.017 0.015 0.   ]
 [0.01  0.029 0.299 0.006 0.579 0.    0.077]
 [0.    0.    0.907 0.002 0.087 0.002 0.001]]


In [52]:
print(LR.classes_)

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']


In [53]:
print(LR.coef_.shape, LR.intercept_.shape)

(7, 5) (7,)


In [54]:
print(LR.coef_, LR.intercept_)  #  hw() = -0.202 - 1.647 x Weight - 1.258 x Length + 2.554 x 'Diagonal + 7.875 x Height - 0.862 x Width

[[-1.64706758 -1.25841952  2.55447067  7.87459099 -0.86224865]
 [ 0.1465012  -1.74426325 -3.68996319  6.57232827 -2.42999442]
 [ 3.64650067  6.76716237 -9.02523542 -5.72691863  3.85465506]
 [-0.06748929  3.58531539  3.90650126 -3.58236001 -1.68456826]
 [-1.43997348 -6.42580006  5.65781158 -0.92092882  1.9410231 ]
 [-1.39170904  1.49468794  1.4025808  -5.77803276 -4.41186249]
 [ 0.75323753 -2.41868287 -0.8061657   1.56132095  3.59299565]] [-0.202041   -0.28565016  3.30614    -0.11930865  2.77161162 -6.93099893
  1.46024711]


In [55]:
decision = LR.decision_function(test_scaled[:5])
print(np.round(decision, decimals=2))

[[ -6.71   0.94   5.32  -2.74   3.37   0.29  -0.47]
 [-11.47   2.05   4.88  -2.46   2.96   7.97  -3.93]
 [ -4.85  -5.99   3.16   6.51   2.48   2.39  -3.69]
 [ -0.7    0.39   2.71  -1.15   3.37  -5.97   1.35]
 [ -6.64  -2.1    5.94  -0.09   3.59  -0.16  -0.54]]


In [57]:
from scipy.special import softmax
proba = softmax(decision, axis=1)
print(np.round(proba, decimals=3))

[[0.    0.011 0.858 0.    0.123 0.006 0.003]
 [0.    0.003 0.043 0.    0.006 0.948 0.   ]
 [0.    0.    0.033 0.935 0.017 0.015 0.   ]
 [0.01  0.029 0.299 0.006 0.579 0.    0.077]
 [0.    0.    0.907 0.002 0.087 0.002 0.001]]
